name: SimplePlayerFreeze
version: '${project.version}'
main: simplexity.simpleplayerfreeze.SimplePlayerFreeze
api-version: '1.20'
commands:
  freeze:
    permission: 'spf.freeze'
  unfreeze:
    permission: 'spf.unfreeze'