name: SimplePlayerFreeze
main: simplexity.simpleplayerfreeze.SimplePlayerFreeze
version: '${project.version}'
api-version: '1.21.5'
author: 'Rhythmic'
website: 'https://github.com/Simplexity-Development/SimplePlayerFreeze'
depend: []
softdepend:
  - PlaceholderAPI
  - DiscordSRV
permissions:
  spf.freeze:
    description: 'Allows the player to freeze other players'
    default: op
  spf.unfreeze:
    description: 'Allows the player to unfreeze other players'
    default: op
  spf.notify:
    description: 'Notifies this player when a frozen player logs in'
    default: op
  spf.bypass:
    description: 'Makes this player immune to being frozen'
    default: op
  spf.reload:
    description: 'Allows this player to reload the configuration'
    default: op
  spf.chatspy:
    description: 'Allows this player to to see muted messages from frozen players'
    default: op
  spf.freezeall:
    description: 'Allows this player to use the /freezeall command'
    default: op
  spf.freezeall.server:
    description: 'Allows this player to freeze all the players in the server'
    default: op
    children:
      spf.freezeall: true
  spf.freezeall.world:
    description: 'Allows this player to freeze all the players in a specific world'
    default: op
    children:
      spf.freezeall: true
  spf.unfreezeall:
    description: 'Allows this player to use the /unfreezeall command'
    default: op
  spf.unfreezeall.server:
    description: 'Allows this player to freeze all players in the server'
    default: op
    children:
      spf.unfreezeall: true
  spf.unfreezeall.world:
    description: 'Allows this player to freeze all players in a specific world'
    default: op
    children:
      spf.unfreezeall: true
commands:
  freeze:
    permission: 'spf.freeze'
    description: 'Freeze a player or unfreeze a frozen player'
    usage: '/freeze <player>'
  unfreeze:
    permission: 'spf.unfreeze'
    description: 'Unfreeze a frozen player'
    usage: '/unfreeze <player>'
  freezeall:
    permission: 'spf.freezeall'
    description: 'Freeze all the players in a server or world'
    usage: '/freezeall [worldname]'
  unfreezeall:
    permission: 'spf.unfreezeall'
    description: 'Unfreeze all players in a server or world'
    usage: '/unfreezeall [worldname]'
  freezespy:
    permission: 'spf.chatspy'
    description: "Toggle personal visibility for frozen player's messages"
    usage: '/fspy'
    alias: 'fspy'
  freezereload:
    permission: 'spf.reload'
    description: 'Reload the configuration of the SPF plugin'
    usage: '/spfreload'
    alias: 'spfreload'