name: SimplePlayerFreeze
main: simplexity.simpleplayerfreeze.SimplePlayerFreeze
version: '${project.version}'
api-version: '1.19'
author: 'Rhythmic'
website: 'https://github.com/Simplexity-Development/SimplePlayerFreeze'
depend: []
softdepend:
  - PlaceholderAPI
permissions:
  spf.freeze:
    description: 'Allows the player to freeze other players'
    default: op
  spf.unfreeze:
    description: 'Allows the player to unfreeze other players'
    default: op
  spf.notify:
    description: 'Notifies this player when a frozen player logs in'
    default: op
  spf.bypass:
    description: 'Makes this player immune to being frozen'
    default: op
  spf.reload:
    description: 'Allows this player to reload the configuration'
    default: op
  spf.chatspy:
    description: 'Allows this player to to see muted messages from frozen players'
    default: op
commands:
  freeze:
    permission: 'spf.freeze'
    description: 'Freeze a player or unfreeze a frozen player'
    usage: '/freeze <player>'
  unfreeze:
    permission: 'spf.unfreeze'
    description: 'Unfreeze a frozen player'
    usage: '/unfreeze <player>'
  freezespy:
    permission: 'spf.chatspy'
    description: "Toggle personal visibility for frozen player's messages"
    usage: '/fspy'
    alias: 'fspy'
  freezereload:
    permission: 'spf.reload'
    description: 'Reload the configuration of the SPF plugin'
    usage: '/spfreload'
    alias: 'spfreload'